name = "Aymara"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ay"

[windows]
system_product_code = "{5D88E203-F4A2-4826-AB24-6F538B85F36D}_is1"
legacy_product_codes = [
    { value = "040C3F94-5670-4BCD-A70D-5353A19A0913", kind = "nsis" },
    { value = "29EED916-7874-4DDF-BA73-9D21DE722D58", kind = "nsis" }
]
