template = "https://github.com/giellalt/template-lang-und"
rev_id = 288
template_sha = "dad1e9d42924a392d25de22e57436619ea3f5f1c"

[replacements]
__GLOTTOLOG_ID__ = "nucl1667"
__REPO__ = "lang-aym"
__UND2C__ = "ay"
__UNDEFINED__ = "Aymara"
__UND__ = "aym"
