template = "https://github.com/giellalt/template-lang-und"
rev_id = 291
template_sha = "4f5759693f3a379d63c31d91878cd6e3b56817ae"

[replacements]
__GLOTTOLOG_ID__ = "nucl1667"
__REPO__ = "lang-aym"
__UND2C__ = "ay"
__UNDEFINED__ = "Aymara"
__UND__ = "aym"
